let allStories=[];let activeCategory="All";let map;let markers=[];
const icons={Restaurant:"🍔",Retail:"🛍️",Housing:"🏡",Roads:"🚧",Business:"🏢"};
fetch("data/stories.json").then(r=>r.json()).then(data=>{allStories=data;buildCityFilter();buildStats();renderFeatured();renderStories();initMap();});
function buildCityFilter(){const cities=[...new Set(allStories.map(s=>s.city))].sort();document.getElementById("cityFilter").innerHTML='<option value="All">All Cities</option>'+cities.map(c=>`<option value="${c}">${c}</option>`).join("");}
function buildStats(){const stats=document.getElementById("stats");const total=allStories.length;const cats=["Restaurant","Retail","Housing"];stats.innerHTML=`<div class="stat"><strong>${total}</strong><span>Tracked Projects</span></div>`+cats.map(c=>`<div class="stat"><strong>${allStories.filter(s=>s.category===c).length}</strong><span>${c}</span></div>`).join("");}
function renderFeatured(){const s=allStories[0];document.getElementById("featured").innerHTML=`<p class="eyebrow">Featured Project</p><h2>${icons[s.category]||"📍"} ${s.title}</h2><p class="meta">📍 ${s.city} • ${s.category} • ${s.status}</p><p>${s.summary}</p><a class="read-more" href="pages/project.html?id=${s.id}">View project →</a>`;}
function filtered(){const q=document.getElementById("searchInput").value.toLowerCase();const city=document.getElementById("cityFilter").value;return allStories.filter(s=>{const txt=`${s.title} ${s.city} ${s.category} ${s.status} ${s.summary}`.toLowerCase();return (activeCategory==="All"||s.category===activeCategory)&&(city==="All"||s.city===city)&&txt.includes(q);});}
function renderStories(){const list=filtered();document.getElementById("resultCount").textContent=`${list.length} result${list.length===1?"":"s"}`;document.getElementById("storyGrid").innerHTML=list.map(s=>`<article class="card"><span class="tag">${icons[s.category]||"📍"} ${s.category}</span><h3>${s.title}</h3><p class="meta">📍 ${s.city} • Updated ${s.updated}</p><p>${s.summary}</p><p class="status">Status: <strong>${s.status}</strong></p><a class="read-more" href="pages/project.html?id=${s.id}">View project →</a></article>`).join("");updateMapMarkers(list);}
document.getElementById("searchInput").addEventListener("input",renderStories);document.getElementById("cityFilter").addEventListener("change",renderStories);
document.querySelectorAll("[data-category]").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("[data-category]").forEach(b=>b.classList.remove("active"));btn.classList.add("active");activeCategory=btn.dataset.category;renderStories();}));
function initMap(){map=L.map("developmentMap").setView([28.0395,-81.7887],10);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenStreetMap"}).addTo(map);updateMapMarkers(allStories);}
function updateMapMarkers(list){if(!map)return;markers.forEach(m=>map.removeLayer(m));markers=list.map(s=>L.marker([s.lat,s.lng]).addTo(map).bindPopup(`<strong>${s.title}</strong><br>${s.city}<br>${s.category} • ${s.status}<br><a href="pages/project.html?id=${s.id}">View project</a>`));}
