const CITIES = ["Auburndale","Bartow","Davenport","Dundee","Eagle Lake","Fort Meade","Frostproof","Haines City","Highland Park","Hillcrest Heights","Lake Alfred","Lake Hamilton","Lakeland","Lake Wales","Mulberry","Polk City","Winter Haven","Unincorporated"];
let allItems = [];
const placeholder = "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80";
function esc(s){return String(s||"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function optionize(id, values){const el=document.getElementById(id); values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o);});}
function card(item, featured=false){const img=item.image||placeholder; const badges=`<div class="badge-row"><span class="badge ${esc(item.category)}">${esc(item.category||'Development')}</span><span class="badge status">${esc(item.status||'Update')}</span></div>`; const link=item.link?`<a class="${featured?'button':'read-more'}" href="${esc(item.link)}" target="_blank" rel="noopener">Read More →</a>`:''; if(featured){return `<img src="${esc(img)}" alt=""><div class="featured-body">${badges}<h3>${esc(item.title)}</h3><p class="meta">📍 ${esc(item.city)} • ${esc(item.date||'')} • ${esc(item.source||'Live source')}</p><p class="summary">${esc(item.summary)}</p>${link}</div>`} return `<article class="news-card"><img src="${esc(img)}" alt=""><div class="news-body">${badges}<h3>${esc(item.title)}</h3><p class="meta">📍 ${esc(item.city)} • ${esc(item.date||'')} • ${esc(item.source||'Live source')}</p><p class="summary">${esc(item.summary)}</p>${link}</div></article>`}
function filterItems(){const city=document.getElementById('cityFilter').value, cat=document.getElementById('categoryFilter').value, status=document.getElementById('statusFilter').value, q=document.getElementById('searchInput').value.toLowerCase(); return allItems.filter(i=>(city==='All'||i.city===city)&&(cat==='All'||i.category===cat)&&(status==='All'||i.status===status)&&(!q||[i.title,i.city,i.category,i.status,i.summary].join(' ').toLowerCase().includes(q)));}
function render(){const items=filterItems();document.getElementById('resultCount').textContent=`${items.length} updates`; const featured=items.find(i=>i.featured)||items[0]; document.getElementById('featuredProject').innerHTML=featured?card(featured,true):'<div class="empty">No matching featured project.</div>'; document.getElementById('newsGrid').innerHTML=items.length?items.map(i=>card(i)).join(''):'<div class="empty">No matching updates yet.</div>';}
async function init(){optionize('cityFilter',CITIES); const cats=["Housing","Restaurant","Retail","Hotel","Commercial","Infrastructure","Community","Development"]; optionize('categoryFilter',cats); optionize('statusFilter',["Planned","Approved","Under Construction","Coming Soon","Grand Opening","Completed","Update"]); try{const res=await fetch('data/news.json?ts='+Date.now()); const data=await res.json(); allItems=data.items||[]; document.getElementById('lastUpdated').textContent='Last updated: '+(data.last_updated||'unknown');}catch(e){allItems=[]; document.getElementById('lastUpdated').textContent='Last updated: unable to load feed';} ['cityFilter','categoryFilter','statusFilter','searchInput'].forEach(id=>document.getElementById(id).addEventListener('input',render)); render();}
init();
